# Generated by Django 3.1 on 2020-08-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FilePathField(path='D:\\roof_node\\cb_task\\product/images'),
        ),
    ]
