# Generated by Django 3.1 on 2020-08-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200812_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(upload_to='D:\\roof_node\\cb_task\\images'),
        ),
    ]
